# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 11:30
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actors', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('director', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('pictur', models.ImageField(upload_to=b'')),
                ('length', models.TimeField()),
                ('release_date', models.DateField()),
                ('rented', models.BooleanField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('pub_date__month',))),
                ('trailer_url', models.URLField()),
                ('synopsis', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AddField(
            model_name='movierent',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Customer'),
        ),
        migrations.AddField(
            model_name='movierent',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Movie'),
        ),
    ]
