# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 12:44
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20181105_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviegenre',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='lebel', unique_with=('pub_date__month',)),
        ),
    ]
