# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 12:46
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20181105_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='label'),
        ),
    ]
