# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20181105_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='pictur',
            new_name='picture',
        ),
    ]
