# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_auto_20181105_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.CharField(max_length=200, null=True, verbose_name='Acteurs'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=100, verbose_name='directeur'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.TimeField(verbose_name='Dur\xe9e'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.ImageField(upload_to=b'', verbose_name='Affiche du filme'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rented',
            field=models.BooleanField(verbose_name='En Location'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(null=True, verbose_name='synopsis'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='movierent',
            name='checkout_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date de l'emprunt"),
        ),
    ]
