# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_auto_20181112_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='Pays')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='titre')),
                ('synopsis', models.TextField(null=True, verbose_name='synopsis')),
                ('genre', models.ManyToManyField(to='bank.MovieGenre')),
            ],
            options={
                'managed': True,
                'db_table': 'bank_movie_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'movie Translation',
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='synopsis',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
        migrations.AddField(
            model_name='movietranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='bank.Movie'),
        ),
        migrations.AlterUniqueTogether(
            name='movietranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
