# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 14:03
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_auto_20181112_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='slug',
        ),
        migrations.AddField(
            model_name='movietranslation',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='a', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
