# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0018_auto_20181112_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='bank.Movie'),
        ),
    ]
